Form per la registrazione e il login
Weather-Vortex/weather-vortex-client pull request #24
Opened 2021-08-15 14:02 UTC by silviazandoli

Allego qui la resa grafica, sono state inserite anche tutte le regole di validazione. La validazione si può vedere nella prima foto, le caselle in quel caso venivano rosse così perchè avevo cliccato sul tasto register senza compilare quei form. E' stata usata la libreria Vuetify. 

![Cattura](https://user-images.githubusercontent.com/29338213/129480966-0f8f7601-e285-45f8-9356-39fd228753d2.PNG)
![Cattura1](https://user-images.githubusercontent.com/29338213/129480969-93f6759f-0e23-4e3b-b24c-e4f06dcada20.PNG)

2021-08-15 15:57 UTC, Daniele-Tentoni requested changes

2021-08-15 15:57 UTC, Daniele-Tentoni commented on src/views/users/Register.vue
> +<div class="login">
If that class is not useful we can remove it.

2021-08-15 15:57 UTC, Daniele-Tentoni commented on src/views/users/Register.vue
> +  <v-container fluid class="fluid">
<v-container fluid> is not enough?

2021-08-15 15:57 UTC, Daniele-Tentoni commented on src/views/users/Login.vue
> +  <div class="login">
If that class is not useful we can remove it.

2021-08-15 15:57 UTC, Daniele-Tentoni commented on src/views/users/Login.vue
> +    <v-container fluid class="fluid">
is not enough?

2021-08-15 17:14 UTC, silviazandoli commented on src/views/users/Login.vue
> +    <v-container fluid class="fluid">
tolto

2021-08-15 17:48 UTC, Daniele-Tentoni commented
@silviazandoli la mia questione riguardante due domande era in merito al fatto che hai aggiunto sia il tag `fluid` che `class="fluid"` in due punti del codice. Qual'è il comportamento che volevi ottenere? Una delle due istruzioni non è superflua/contraddittoria rispetto l'altra? Oppure la classe di stile `fluid` fa qualcosa che dovrebbe essere chiamato in altro modo?

2021-08-15 18:11 UTC, silviazandoli commented
@Daniele-Tentoni è proprio una piccolezza, però se metto due fluid viene proprio centrato perfettamente. lasciando solo class="fluid" il form si sposta leggermente verso sinistra

2021-08-16 07:52 UTC, silviazandoli commented
@Daniele-Tentoni ho risolto. Ho messo fluid solo al container e riesco a ottenere l'effetto centrale desiderato

2021-08-16 09:55 UTC, Daniele-Tentoni approved these changes

2021-08-16 09:55 UTC, merged